import { StyleSheet } from 'react-native';
import { AppTheme } from '@/styles/app-theme';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: AppTheme.colors.pageBg,
  },
  content: {
    paddingHorizontal: AppTheme.spacing.xl,
    paddingTop: 16,
    paddingBottom: AppTheme.spacing.pageBottomInset,
    gap: AppTheme.spacing.lg,
  },
  testCard: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.radius.lg,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
    padding: AppTheme.spacing.md,
    gap: AppTheme.spacing.sm,
  },
  testHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  testTitle: {
    fontSize: AppTheme.fontSize.titleSm,
    color: AppTheme.colors.textPrimary,
    fontWeight: '700',
  },
  testStatus: {
    fontSize: AppTheme.fontSize.md,
    fontWeight: '800',
    color: AppTheme.colors.textMuted,
  },
  testStatusOk: {
    color: AppTheme.colors.success,
  },
  testStatusFail: {
    color: AppTheme.colors.danger,
  },
  testMessage: {
    fontSize: AppTheme.fontSize.body,
    color: AppTheme.colors.textSecondary,
  },
  testButton: {
    alignSelf: 'flex-start',
    backgroundColor: AppTheme.colors.primary,
    borderRadius: AppTheme.radius.sm,
    paddingHorizontal: AppTheme.spacing.md,
    paddingVertical: AppTheme.spacing.sm,
  },
  testButtonText: {
    color: AppTheme.colors.surface,
    fontSize: 12,
    fontWeight: '700',
  },
  payloadText: {
    marginTop: AppTheme.spacing.xs,
    fontSize: 11,
    color: AppTheme.colors.textPrimary,
    backgroundColor: AppTheme.colors.pageBg,
    borderRadius: AppTheme.radius.sm,
    padding: AppTheme.spacing.sm,
    fontFamily: 'monospace',
  },
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 12,
  },
  heading: {
    marginTop: 2,
    fontSize: AppTheme.fontSize.hero,
    fontWeight: '800',
    color: AppTheme.colors.textPrimary,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: AppTheme.fontSize.md,
    paddingVertical: 6,
    borderRadius: AppTheme.radius.md,
    backgroundColor: AppTheme.colors.border,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: AppTheme.colors.liveDot,
  },
  liveText: {
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: AppTheme.colors.textSecondary,
    fontWeight: '600',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  statCard: {
    width: '31%',
    minWidth: 104,
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.radius.lg,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
    paddingHorizontal: AppTheme.spacing.md,
    paddingVertical: 10,
  },
  statLabel: {
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: AppTheme.colors.textMuted,
    fontWeight: '600',
  },
  statValueRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '900',
  },
  statSub: {
    marginTop: 3,
    color: AppTheme.colors.textMuted,
    fontSize: 8,
  },
  sectionHeader: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: AppTheme.fontSize.heading,
    color: AppTheme.colors.textPrimary,
    fontWeight: '800',
  },
  sectionAction: {
    color: AppTheme.colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  packagesWrap: {
    gap: 10,
  },
  packageCard: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.radius.lg,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
    padding: AppTheme.spacing.lg,
    gap: 10,
  },
  packageMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  packageIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  packageName: {
    fontSize: 16,
    color: AppTheme.colors.textPrimary,
    fontWeight: '700',
  },
  packageId: {
    marginTop: 2,
    color: AppTheme.colors.textMuted,
    fontSize: 12,
  },
  packageMeta: {
    gap: 6,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationText: {
    color: AppTheme.colors.textSecondary,
    fontSize: 12,
  },
  progressTrack: {
    height: 6,
    borderRadius: AppTheme.radius.sm,
    backgroundColor: AppTheme.colors.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
  },
  damageText: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: AppTheme.colors.textMuted,
    fontWeight: '700',
  },
  packageRight: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusPill: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: AppTheme.radius.pill,
    overflow: 'hidden',
  },
  alertCard: {
    marginTop: 2,
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.radius.lg,
    borderWidth: 1,
    borderColor: '#FECACA',
    padding: AppTheme.spacing.lg,
    gap: 10,
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  alertTitle: {
    fontSize: 18,
    color: AppTheme.colors.textPrimary,
    fontWeight: '800',
  },
  alertItem: {
    borderLeftWidth: 2,
    paddingLeft: 10,
    gap: 4,
  },
  alertType: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '800',
  },
  alertMessage: {
    fontSize: 14,
    color: AppTheme.colors.textPrimary,
    lineHeight: 20,
  },
  alertTime: {
    fontSize: 11,
    color: AppTheme.colors.textMuted,
    textTransform: 'uppercase',
  },
  mapCard: {
    backgroundColor: AppTheme.colors.surface,
    borderRadius: AppTheme.radius.lg,
    borderWidth: 1,
    borderColor: AppTheme.colors.border,
    overflow: 'hidden',
  },
  mapView: {
    height: 170,
  },
  mapFooter: {
    padding: AppTheme.spacing.md,
  },
  mapTitle: {
    color: AppTheme.colors.textPrimary,
    fontSize: AppTheme.fontSize.title,
    fontWeight: '700',
  },
  mapSub: {
    marginTop: 2,
    color: AppTheme.colors.textMuted,
    fontSize: 12,
  },
});
