import { StyleSheet } from 'react-native';

import type { ThemeColors } from '@/styles/app-theme';
import { themeBase as t } from '@/styles/app-theme';

export function createDashboardStyles(c: ThemeColors) {
  return StyleSheet.create({
    page: {
      flex: 1,
      backgroundColor: c.pageBg,
    },
    content: {
      paddingHorizontal: t.spacing.xl,
      paddingTop: 10,
      paddingBottom: t.spacing.pageBottomInset,
      gap: 10,
    },
    testCard: {
      backgroundColor: c.surface,
      borderRadius: t.radius.md,
      borderWidth: 1,
      borderColor: c.border,
      padding: t.spacing.sm,
      gap: 6,
    },
    testHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    testTitle: {
      fontSize: t.fontSize.titleSm,
      color: c.textPrimary,
      fontWeight: '700',
    },
    testStatus: {
      fontSize: t.fontSize.md,
      fontWeight: '800',
      color: c.textMuted,
    },
    testStatusOk: {
      color: c.success,
    },
    testStatusFail: {
      color: c.danger,
    },
    testMessage: {
      fontSize: t.fontSize.body,
      color: c.textSecondary,
    },
    testButton: {
      alignSelf: 'flex-start',
      backgroundColor: c.primary,
      borderRadius: t.radius.sm,
      paddingHorizontal: t.spacing.md,
      paddingVertical: t.spacing.sm,
    },
    testButtonText: {
      color: c.surface,
      fontSize: 12,
      fontWeight: '700',
    },
    heroRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    heading: {
      marginTop: 2,
      fontSize: t.fontSize.heading,
      fontWeight: '800',
      color: c.textPrimary,
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 10,
    },
    statCard: {
      width: '31%',
      minWidth: 104,
      backgroundColor: c.surface,
      borderRadius: t.radius.lg,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: t.spacing.sm,
      paddingVertical: 8,
    },
    statLabel: {
      fontSize: 9,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      color: c.textMuted,
      fontWeight: '600',
    },
    statValueRow: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
      width: '100%',
    },
    statValue: {
      flex: 1,
      minWidth: 0,
      fontSize: 18,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
    },
    overviewColumn: {
      flex: 1,
      paddingHorizontal: t.spacing.xl,
      paddingTop: 6,
      paddingBottom: t.spacing.pageBottomInset,
      gap: 8,
      minHeight: 0,
    },
    deviceScroll: {
      flex: 1,
      minHeight: 100,
    },
    deviceScrollContent: {
      gap: 8,
      paddingBottom: 6,
      width: '100%',
      alignItems: 'stretch',
    },
    devicesRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      minHeight: 0,
    },
    filterChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: t.radius.pill,
      backgroundColor: `${c.primary}22`,
      borderWidth: 1,
      borderColor: `${c.primary}55`,
    },
    filterChipText: {
      fontSize: 10,
      fontWeight: '800',
      color: c.primary,
      letterSpacing: 0.6,
    },
    activitySection: {
      gap: 4,
    },
    activityCaption: {
      fontSize: 9,
      fontWeight: '700',
      color: c.textMuted,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    activityRangeLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: c.primary,
      marginTop: 1,
      marginBottom: 1,
      fontVariant: ['tabular-nums'],
    },
    activityTrack: {
      height: 34,
      position: 'relative',
      marginTop: 2,
    },
    activityBaseline: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 2,
      borderRadius: 1,
      backgroundColor: c.border,
    },
    activityDot: {
      position: 'absolute',
      bottom: 3,
      width: 3,
      height: 11,
      borderRadius: 1.5,
      backgroundColor: c.primary,
    },
    activityHitRow: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
    },
    activityHitCell: {
      flex: 1,
    },
    activityHitCellSelected: {
      backgroundColor: `${c.primary}14`,
      borderRadius: 4,
    },
    mixSection: {
      gap: 6,
    },
    mixLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: c.textMuted,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    mixDonutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      minHeight: 0,
    },
    mixDonutSvgWrap: {
      width: 120,
      height: 120,
    },
    mixLegendCol: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    mixLegendLine: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    mixLegendSwatch: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    mixLegendItemText: {
      flex: 1,
      fontSize: 10,
      fontWeight: '700',
      color: c.textSecondary,
    },
    mixLegendPct: {
      fontSize: 10,
      fontWeight: '800',
      color: c.textMuted,
    },
    sectionHeader: {
      marginTop: 4,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    sectionTitle: {
      fontSize: t.fontSize.heading,
      color: c.textPrimary,
      fontWeight: '800',
    },
    sectionAction: {
      color: c.primary,
      fontSize: 12,
      fontWeight: '600',
    },
    packagesWrap: {
      gap: 8,
    },
    packageCard: {
      width: '100%',
      alignSelf: 'stretch',
      backgroundColor: c.surface,
      borderRadius: t.radius.md,
      borderWidth: 1,
      borderColor: c.border,
      padding: t.spacing.md,
      gap: 8,
    },
    packageMain: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    packageIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    packageName: {
      fontSize: 16,
      color: c.textPrimary,
      fontWeight: '700',
    },
    packageLocationInline: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      color: c.textMuted,
      fontStyle: 'italic',
      fontWeight: '600',
    },
    packageInfoIconCol: {
      width: 14,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      paddingTop: 1,
    },
    packageInfoBody: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      gap: 4,
      minWidth: 0,
    },
    packageInfoLabelSlot: {
      alignItems: 'flex-start',
    },
    packageMetaLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: c.textSecondary,
      letterSpacing: 0.2,
    },
    packageInfoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 4,
      width: '100%',
      alignSelf: 'stretch',
    },
    packageInfoValueLine: {
      flex: 1,
      minWidth: 0,
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 15,
    },
    packageInfoType: {
      fontSize: 11,
      fontWeight: '700',
    },
    packageInfoMutedSmall: {
      color: c.textSecondary,
      fontWeight: '600',
      fontSize: 11,
    },
    packageMeta: {
      gap: 6,
      width: '100%',
      alignSelf: 'stretch',
    },
    damageText: {
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      color: c.textMuted,
      fontWeight: '700',
    },
    packageRight: {
      marginTop: 4,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    statusPill: {
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: t.radius.pill,
      overflow: 'hidden',
    },
    alertCard: {
      marginTop: 2,
      backgroundColor: c.surface,
      borderRadius: t.radius.lg,
      borderWidth: 1,
      borderColor: c.alertBorder,
      padding: t.spacing.lg,
      gap: 10,
    },
    alertCardCompact: {
      marginTop: 0,
      paddingVertical: 10,
      paddingHorizontal: t.spacing.md,
      gap: 6,
    },
    alertHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    alertTitle: {
      fontSize: 18,
      color: c.textPrimary,
      fontWeight: '800',
    },
    alertTitleCompact: {
      fontSize: 13,
    },
    alertItem: {
      borderLeftWidth: 2,
      paddingLeft: 10,
      gap: 4,
    },
    alertType: {
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 1,
      fontWeight: '800',
    },
    alertMessage: {
      fontSize: 14,
      color: c.textPrimary,
      lineHeight: 20,
    },
    alertMessageCompact: {
      fontSize: 12,
      lineHeight: 16,
    },
    alertTime: {
      fontSize: 11,
      color: c.textMuted,
      textTransform: 'uppercase',
    },
  });
}

export type DashboardStyles = ReturnType<typeof createDashboardStyles>;
